version: "3"
services:
  # Database
  postgres-user:
    build:
      context: .
      dockerfile: postgres-user/postgres-user.Dockerfile
    environment:
      POSTGRES_PASSWORD: buzzni-assignment
    image: buzzni-assignment/postgres-user
    ports:
      - "35432:5432"

  postgres-alarm:
    build:
      context: .
      dockerfile: postgres-alarm/postgres-alarm.Dockerfile
    environment:
      POSTGRES_PASSWORD: buzzni-assignment
    image: buzzni-assignment/postgres-alarm
    ports:
      - "35433:5432"

  postgres-item:
    build:
      context: .
      dockerfile: postgres-item/postgres-item.Dockerfile
    environment:
      POSTGRES_PASSWORD: buzzni-assignment
    image: buzzni-assignment/postgres-item
    ports:
      - "35434:5432"

  # API
  api-user:
    build:
      context: .
      dockerfile: api-user/api-user.Dockerfile
    image: buzzni-assignment/api-user
    ports:
      - "7001:7001"

  api-alarm:
    build:
      context: .
      dockerfile: api-alarm/api-alarm.Dockerfile
    image: buzzni-assignment/api-alarm
    ports:
      - "6001:6001"

  api-item:
    build:
      context: .
      dockerfile: api-item/api-item.Dockerfile
    image: buzzni-assignment/api-item
    ports:
      - "5001:5001"
